<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bansos_model extends CI_Model
{
    protected $table = 'bansos';
    protected $bansos_nama = 'bansos_nama';
    function __construct()
    {
        parent::__construct();
    }
    
    public function filter($search, $limit, $start, $order_field, $order_ascdesc){
        $this->db->like($this->bansos_nama, $search); // Untuk menambahkan query where LIKE
        $this->db->order_by($order_field, $order_ascdesc); // Untuk menambahkan query ORDER BY
        $this->db->limit($limit, $start); // Untuk menambahkan query LIMIT
        return $this->db->get($this->table)->result_array(); // Eksekusi query sql sesuai kondisi diatas
    }
    public function count_all(){
        return $this->db->count_all($this->table); // Untuk menghitung semua data siswa
    }
    public function count_filter($search){
        $this->db->like($this->bansos_nama, $search); // Untuk menambahkan query where OR LIKE
        return $this->db->get($this->table)->num_rows(); // Untuk menghitung jumlah data sesuai dengan filter pada textbox pencarian
    }
    
    /*
     * Get bansos by bansos_id
     */
    function get_bansos($bansos_id)
    {
        return $this->db->get_where($this->table,array('bansos_id'=>$bansos_id))->row_array();
    }
    
    /*
     * Get all bansos count
     */
    function get_all_bansos_count()
    {
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bansos
     */
    function get_all_bansos($params = [])
    {
        $this->db->order_by('bansos_id', 'desc');
        if(isset($params) && !empty($params))
        {
          $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get($this->table)->result_array();
    }
        
    /*
     * function to add new bansos
     */
    function add_bansos($params)
    {
        $this->db->insert($this->table,$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bansos
     */
    function update_bansos($bansos_id,$params)
    {
        $this->db->where('bansos_id',$bansos_id);
        return $this->db->update($this->table,$params);
    }
    
    /*
     * function to delete bansos
     */
    function delete_bansos($bansos_id)
    {
        return $this->db->delete($this->table,array('bansos_id'=>$bansos_id));
    }
    function seed()
    {
        $data = [
            ["bansos_nama" => "APBN"],
            ["bansos_nama" => "APBD PROP"],
            ["bansos_nama" => "APBD KAB"],
            ["bansos_nama" => "TIDAK ADA"],
        ];

        $this->db->insert_batch($this->table, $data);
    }
}