<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategori_ot_model extends CI_Model
{
    protected $table = 'kategori_ot';
    protected $kategori_ot_nama = 'kategori_ot_nama';
    function __construct()
    {
        parent::__construct();
    }
    
    public function filter($search, $limit, $start, $order_field, $order_ascdesc){
        $this->db->like($this->kategori_ot_nama, $search); // Untuk menambahkan query where LIKE
        $this->db->order_by($order_field, $order_ascdesc); // Untuk menambahkan query ORDER BY
        $this->db->limit($limit, $start); // Untuk menambahkan query LIMIT
        return $this->db->get($this->table)->result_array(); // Eksekusi query sql sesuai kondisi diatas
    }
    public function count_all(){
        return $this->db->count_all($this->table); // Untuk menghitung semua data siswa
    }
    public function count_filter($search){
        $this->db->like($this->kategori_ot_nama, $search); // Untuk menambahkan query where OR LIKE
        return $this->db->get($this->table)->num_rows(); // Untuk menghitung jumlah data sesuai dengan filter pada textbox pencarian
    }
    
    /*
     * Get kategori_ot by kategori_ot_id
     */
    function get_kategori_ot($kategori_ot_id)
    {
        return $this->db->get_where($this->table,array('kategori_ot_id'=>$kategori_ot_id))->row_array();
    }
    
    /*
     * Get all kategori_ot count
     */
    function get_all_kategori_ot_count()
    {
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
        
    /*
     * Get all kategori_ot
     */
    function get_all_kategori_ot($params = [])
    {
        $this->db->order_by('kategori_ot_id', 'desc');
        if(isset($params) && !empty($params))
        {
          $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get($this->table)->result_array();
    }
        
    /*
     * function to add new kategori_ot
     */
    function add_kategori_ot($params)
    {
        $this->db->insert($this->table,$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kategori_ot
     */
    function update_kategori_ot($kategori_ot_id,$params)
    {
        $this->db->where('kategori_ot_id',$kategori_ot_id);
        return $this->db->update($this->table,$params);
    }
    
    /*
     * function to delete kategori_ot
     */
    function delete_kategori_ot($kategori_ot_id)
    {
        return $this->db->delete($this->table,array('kategori_ot_id'=>$kategori_ot_id));
    }
    function seed()
    {
        $this->db->truncate($this->table);
        $data = [
            ["kategori_ot_nama" => "ANAK-ANAK"],
            ["kategori_ot_nama" => "DEWASA"],
            ["kategori_ot_nama" => "LANSIA"],
        ];

        $this->db->insert_batch($this->table, $data);
    }
}