<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Login_admin_model extends CI_Model
{
  protected $table = 'login_admin';
  function __construct()
  {
    parent::__construct();
  }
  /*
     * Get all admin
     */
  function get_all_login_admin($params = [])
  {
    $this->db->order_by('admin_id', 'desc');
    if (isset($params) && !empty($params)) {
      $this->db->limit($params['limit'], $params['offset']);
      if (isset($params['where'])) {
        $this->db->where($params['where']);
      }
      if (isset($params['order_by'])) {
        $this->db->order_by($params['order_by'], $params['order_by_do']);
      }
    }
    return $this->db->get($this->table)->result_array();
  }
  public function filter($search, $limit, $start, $order_field, $order_ascdesc, $where = NULL)
  {
    $this->db->order_by($order_field, $order_ascdesc); // Untuk menambahkan query ORDER BY
    $this->db->limit($limit, $start); // Untuk menambahkan query LIMIT
    if ($where != NULL) {
      $this->db->where($where);
    }
    return $this->db->get($this->table)->result_array(); // Eksekusi query sql sesuai kondisi diatas
  }
  public function count_all($where = NULL)
  {
    if ($where != NULL) {
      $this->db->where($where);
    }
    $this->db->from($this->table);
    $data = $this->db->get()->num_rows();
    return $data; // Untuk menghitung semua data siswa
  }
  public function count_filter($search, $where = NULL)
  {
    if ($where != NULL) {
      $this->db->where($where);
    }
    return $this->db->get($this->table)->num_rows(); // Untuk menghitung jumlah data sesuai dengan filter pada textbox pencarian
  }

  /*
     * function to add new admin
     */
  function add_login_admin($params)
  {
    $params['created_at'] = date('Y-m-d H:i:s');
    $this->db->insert($this->table, $params);
    return true;
  }
}
