<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sumber_dana_model extends CI_Model
{
    protected $table = 'sumber_dana';
    protected $sumber_dana_nama = 'sumber_dana_nama';
    function __construct()
    {
        parent::__construct();
    }
    
    public function filter($search, $limit, $start, $order_field, $order_ascdesc){
        $this->db->like($this->sumber_dana_nama, $search); // Untuk menambahkan query where LIKE
        $this->db->order_by($order_field, $order_ascdesc); // Untuk menambahkan query ORDER BY
        $this->db->limit($limit, $start); // Untuk menambahkan query LIMIT
        return $this->db->get($this->table)->result_array(); // Eksekusi query sql sesuai kondisi diatas
    }
    public function count_all(){
        return $this->db->count_all($this->table); // Untuk menghitung semua data siswa
    }
    public function count_filter($search){
        $this->db->like($this->sumber_dana_nama, $search); // Untuk menambahkan query where OR LIKE
        return $this->db->get($this->table)->num_rows(); // Untuk menghitung jumlah data sesuai dengan filter pada textbox pencarian
    }
    
    /*
     * Get sumber_dana by sumber_dana_id
     */
    function get_sumber_dana($sumber_dana_id)
    {
        return $this->db->get_where($this->table,array('sumber_dana_id'=>$sumber_dana_id))->row_array();
    }
    
    /*
     * Get all sumber_dana count
     */
    function get_all_sumber_dana_count()
    {
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }
        
    /*
     * Get all sumber_dana
     */
    function get_all_sumber_dana($params = [])
    {
        $this->db->order_by('sumber_dana_id', 'desc');
        if(isset($params) && !empty($params))
        {
          $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get($this->table)->result_array();
    }
        
    /*
     * function to add new sumber_dana
     */
    function add_sumber_dana($params)
    {
        $this->db->insert($this->table,$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sumber_dana
     */
    function update_sumber_dana($sumber_dana_id,$params)
    {
        $this->db->where('sumber_dana_id',$sumber_dana_id);
        return $this->db->update($this->table,$params);
    }
    
    /*
     * function to delete sumber_dana
     */
    function delete_sumber_dana($sumber_dana_id)
    {
        return $this->db->delete($this->table,array('sumber_dana_id'=>$sumber_dana_id));
    }
    function seed()
    {
        $data = [
            ["sumber_dana_nama" => "APBN"],
            ["sumber_dana_nama" => "APBD PROP"],
            ["sumber_dana_nama" => "APBD KAB"],
        ];

        $this->db->insert_batch($this->table, $data);
    }
}