<?php

/* 

 * Generated by CRUDigniter v3.2 

 * www.crudigniter.com

 */
class Terlantar_verif_model extends CI_Model

{

    protected $table = 'terlantar_verif';

    function __construct()

    {
        parent::__construct();
    }

    function get_all_terlantar_verif()

    {
        return $this->db->get($this->table)->result_array();
    }

    function get_all_terlantar_verif_id()

    {
        $this->db->select('terlantar_id');
        $verifes = $this->db->get($this->table)->result_array();
        $data = [];
        foreach ($verifes as $verif) {
            array_push($data, $verif['terlantar_id']);
        }
        return $data;
    }

    function add_terlantar_verif($terlantar_id, $admin_id)

    {
        $this->db->insert($this->table, ['terlantar_id' => $terlantar_id, 'verif_by' => $admin_id, 'verif_at' => date('Y-m-d H:i:s')]);
        return $this->db->insert_id();
    }

    public function is_using($kolom, $id)

    {
        $data = $this->db->get_where($this->table, array($kolom => $id))->row_array();
        if ($data) {
            return true;
        } else {
            return false;
        }
    }

    function delete_terlantar_verif($terlantar_id)

    {
        return $this->db->delete($this->table, array('terlantar_id' => $terlantar_id));
    }

    public function count_all()
    {
        return $this->db->count_all($this->table); // Untuk menghitung semua data siswa

    }
}
